routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('setlocale/{locale}',function($lang){
    if (! in_array($lang, ['en', 'fr'])) {
        abort(400);
    }
    Session::put('locale',$lang);
    return redirect()->back();
});

Route::group(['middleware' => ['language']], function () {
    Auth::routes();
    Route::get('/', 'WelcomeController@index');
    Route::get('/categories/{id}-{name}/products', 'WelcomeController@productOfCategory');
    Route::get('products/{id}', 'ProductController@show');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::prefix('deep')->name('deep.')->namespace('Deep')->group(function () {
        Auth::routes(['register' => false,'reset' => false, 'verify' => false]);

        Route::middleware('auth:deep')->group( function () {

            Route::get('/home', 'HomeController@index')->name('home');

            //Products routes
            Route::get('/products', 'ProductController@index')->name('products');
            Route::get('/products/summary', 'ProductController@summary')->name('products.summary');
            Route::get('/products/add', 'ProductController@create')->name('products.add');
            Route::get('/products/{id}', 'ProductController@show')->name('products.show');
            Route::get('/products/{id}/edit', 'ProductController@edit')->name('products.edit');
            Route::post('/products', 'ProductController@store')->name('products.store');
            Route::put('/products/{id}', 'ProductController@update')->name('products.update');
            Route::delete('/products/{id}', 'ProductController@destroy')->name('products.delete');

            //Orders routes
            Route::get('/orders', 'OrderController@index')->name('orders');
            Route::get('/orders/add', 'OrderController@create')->name('orders.add');
            Route::get('/orders/{id}', 'OrderController@show')->name('orders.show');
            Route::get('/orders/{id}/edit', 'OrderController@edit')->name('orders.edit');
            Route::post('/orders', 'OrderController@store')->name('orders.store');
            Route::put('/orders/{id}', 'OrderController@update')->name('orders.update');

            //Categories routes
            Route::get('/categories', 'CategoryController@index')->name('categories');
            Route::get('/categories/add', 'CategoryController@create')->name('categories.add');
            Route::get('/categories/{id}', 'CategoryController@show')->name('categories.show');
            Route::get('/categories/{id}/edit', 'CategoryController@edit')->name('categories.edit');
            Route::post('/categories', 'CategoryController@store')->name('categories.store');
            Route::put('/categories/{id}', 'CategoryController@update')->name('categories.update');

            //Countries routes
            Route::get('/countries', 'CountryController@index')->name('countries');
            Route::get('/countries/add', 'CountryController@create')->name('countries.add');
            Route::get('/countries/{id}', 'CountryController@show')->name('countries.show');
            Route::get('/countries/{id}/edit', 'CountryController@edit')->name('countries.edit');
            Route::post('/countries', 'CountryController@store')->name('countries.store');
            Route::put('/countries/{id}', 'CountryController@update')->name('countries.update');

            //Sellers routes
            Route::get('/sellers', 'SellerController@index')->name('sellers');
            Route::get('/sellers/add', 'SellerController@create')->name('sellers.add');
            Route::get('/sellers/{id}', 'SellerController@show')->name('sellers.show');
            Route::get('/sellers/{id}/edit', 'SellerController@edit')->name('sellers.edit');
            Route::post('/sellers', 'SellerController@store')->name('sellers.store');
            Route::put('/sellers/{id}', 'SellerController@update')->name('sellers.update');
            Route::delete('/sellers/{id}', 'SellerController@destroy')->name('sellers.delete');

            //Images routes
            Route::post('/images', 'ImageController@store')->name('images.store');
            Route::delete('/images/{id}', 'ImageController@delete')->name('images.delete');

            //Videos routes
            Route::post('/videos', 'VideoController@store')->name('videos.store');
            Route::delete('/videos/{id}', 'VideoController@delete')->name('videos.delete');
            Route::put('/videos/{id}', 'VideoController@update')->name('videos.update');
        });
    });
});

app/Http/Controllers/Deep/CountryController.php
<?php

namespace App\Http\Controllers\Deep;

use App\Http\Controllers\Controller;
use App\Http\Requests\CountryStoreRequest;
use App\Http\Requests\CountryUpdateRequest;
use App\Model\Country;
use Illuminate\Http\Request;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $countries = Country::all();
        return view ('admin.countries.index',['countries' => $countries]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view ('admin.countries.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CountryStoreRequest $request)
    {
        $country = new Country();
        $country->name = $request->name;
        $country->phone_code = $request->phone_code;
        $country->save();
        return redirect(route('deep.countries'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $country = Country::find($id);
        return view ('admin.countries.edit',['country' => $country]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CountryUpdateRequest $request, $id)
    {
        $country = Country::find($id);
        if(isset($request->name)){
            $country->name = $request->name;
        }
        if(isset($request->phone_code)){
            $country->phone_code = $request->phone_code;
        }
        $country->save();
        return redirect(route('deep.countries'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/countries/add.blade.php
@extends('admin.layouts.app')

@section('content')
<h2>{{ __('Countries Management') }}</h2>

<div class="card my-4">
    <div class="card-header">
        <h6>
            <i class="fas fa-fw fa-table"></i>
            {{ __('Form of countries') }}
        </h6>
    </div>
    <div class="card-body">
        @isset($errors)
            @foreach($errors->all() as $error)
            <small class="text-danger">{{$error}}</small><br>
            @endforeach
        @endisset
        <form action="{{ route('deep.countries.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                        <label for="name">{{ __('Name') }}</label>
                        <input type="text" id="name" name="name" class="form-control  @error('name') is-invalid @enderror"  autocomplete="name"  value="{{ old('name') }}" required autofocus>
                        @error('name')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>

                    <div class="col-sm-12 col-md-6">
                        <label for="phone_code">{{ __('Phone prefix') }}</label>
                        <input type="text" id="phone_code" name="phone_code" class="form-control  @error('phone_code') is-invalid @enderror" autocomplete="phone_code"  value="{{ old('phone_code') }}" required>
                        @error('phone_code')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                </div>
            </div>
            <button class="btn btn-success" type="submit">{{ __('Submit') }}</button>
        </form>
    </div>
</div>
@endsection

@section('category-active')active @endsection

resources/views/admin/countries/edit.blade.php
@extends('admin.layouts.app')

@section('content')
<h2>{{ __('Countries Management') }}</h2>

<div class="card my-4">
    <div class="card-header">
        <h6>
            <i class="fas fa-fw fa-table"></i>
            {{ __('Form of countries') }}
        </h6>
    </div>
    <div class="card-body">
        @isset($errors)
            @foreach($errors->all() as $error)
            <small class="text-danger">{{$error}}</small><br>
            @endforeach
        @endisset
        <form action="{{ route('deep.countries.update',$country->id) }}" method="POST">
            @csrf
            @method('put')
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                        <label for="name">{{ __('Name') }}</label>
                        <input type="text" id="name" name="name" class="form-control  @error('name') is-invalid @enderror"  autocomplete="name"  value="{{ $country->name }}" autofocus>
                        @error('name')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>

                    <div class="col-sm-12 col-md-6">
                        <label for="phone_code">{{ __('Phone prefix') }}</label>
                        <input type="text" id="phone_code" name="phone_code" class="form-control  @error('phone_code') is-invalid @enderror" autocomplete="phone_code"  value="{{ $country->phone_code }}">
                        @error('phone_code')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                    </div>
                </div>
            </div>
            <button class="btn btn-success" type="submit">{{ __('Submit') }}</button>
        </form>
    </div>
</div>
@endsection

@section('category-active')active @endsection

resources/views/admin/countries/index.blade.php
@extends('admin.layouts.app')

@section('content')
<h2>{{ __('Countries Management') }}</h2>

<a href="{{ route('deep.countries.add') }}" class="btn btn-success"><i class="fa fa-fw fa-plus"></i> {{ __('Add') }}</a>

<div class="card my-4">
    <div class="card-header">
        <h6>
            <i class="fas fa-fw fa-table"></i>
            {{ __('Table of countries') }}
        </h6>
    </div>
    <div class="card-body">
        @isset($countries)
            @if (count($countries) > 0)
                <table class="table table-bordered table-responsive-md">
                    <thead>
                        <tr>
                            <th>{{ __('Name') }}</th>
                            <th>{{ __('Phone Prefix') }}</th>
                            <th>{{ __('Users count') }}</th>
                            <th>{{ __('Actions') }}</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>{{ __('Name') }}</th>
                            <th>{{ __('Phone Prefix') }}</th>
                            <th>{{ __('Users count') }}</th>
                            <th>{{ __('Actions') }}</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($countries as $country)
                        <tr>
                            <td>{{ $country->name }}</td>
                            <td>{{ $country->phone_code }} <i class="{{ $country->phone_code }}"></i></td>
                            <td>{{ count($country->users) }}</td>
                            <td>
                                <div class="row px-3 justify-content-arround">
                                    <a href="{{ route( 'deep.countries.show' , $country->id ) }}" class="btn btn-primary rounded mr-1 mb-1"><i class="fas fa-file"></i></a>
                                    <a href="{{ route( 'deep.countries.edit' , $country->id ) }}" class="btn btn-warning rounded mr-1 mb-1"><i class="fas fa-pen"></i></a>
                                    <button class="btn btn-danger rounded mr-1 mb-1"><i class="fas fa-trash"></i></button>
                                </div>
                            </td>
                        </tr>    
                        @endforeach
                    </tbody>
                    
                </table>
            @else
            <div class="alert alert-info">
                <h3>{{ __('Info') }}</h3>
                <p>{{ __('No country found in the database') }}</p>
            </div>
            @endif
        @else
        <div class="alert alert-danger">
            <h3>{{ __('Error') }}</h3>
            <p>{{ __('We have been unable to fetch countries data') }}</p>
        </div>
        @endisset
    </div>
</div>
@endsection

@section('country-active')active @endsection