routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Session;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('setlocale/{locale}',function($lang){
    if (! in_array($lang, ['en', 'fr'])) {
        abort(400);
    }
    Session::put('locale',$lang);
    return redirect()->back();
});

Route::group(['middleware' => ['language']], function () {
    Auth::routes();
    Route::get('/', 'WelcomeController@index');
    Route::get('/categories/{id}-{name}/products', 'WelcomeController@productOfCategory');
    Route::get('products/{id}', 'ProductController@show');
    Route::get('/home', 'HomeController@index')->name('home');

    Route::prefix('deep')->name('deep.')->namespace('Deep')->group(function () {
        Auth::routes(['register' => false,'reset' => false, 'verify' => false]);

        Route::middleware('auth:deep')->group( function () {

            Route::get('/home', 'HomeController@index')->name('home');

            //Products routes
            Route::get('/products', 'ProductController@index')->name('products');
            Route::get('/products/summary', 'ProductController@summary')->name('products.summary');
            Route::get('/products/add', 'ProductController@create')->name('products.add');
            Route::get('/products/{id}', 'ProductController@show')->name('products.show');
            Route::get('/products/{id}/edit', 'ProductController@edit')->name('products.edit');
            Route::post('/products', 'ProductController@store')->name('products.store');
            Route::put('/products/{id}', 'ProductController@update')->name('products.update');
            Route::delete('/products/{id}', 'ProductController@destroy')->name('products.delete');

            //Orders routes
            Route::get('/orders', 'OrderController@index')->name('orders');
            Route::get('/orders/add', 'OrderController@create')->name('orders.add');
            Route::get('/orders/{id}', 'OrderController@show')->name('orders.show');
            Route::get('/orders/{id}/edit', 'OrderController@edit')->name('orders.edit');
            Route::post('/orders', 'OrderController@store')->name('orders.store');
            Route::put('/orders/{id}', 'OrderController@update')->name('orders.update');

            //Categories routes
            Route::get('/categories', 'CategoryController@index')->name('categories');
            Route::get('/categories/add', 'CategoryController@create')->name('categories.add');
            Route::get('/categories/{id}', 'CategoryController@show')->name('categories.show');
            Route::get('/categories/{id}/edit', 'CategoryController@edit')->name('categories.edit');
            Route::post('/categories', 'CategoryController@store')->name('categories.store');
            Route::put('/categories/{id}', 'CategoryController@update')->name('categories.update');

            //Countries routes
            Route::get('/countries', 'CountryController@index')->name('countries');
            Route::get('/countries/add', 'CountryController@create')->name('countries.add');
            Route::get('/countries/{id}', 'CountryController@show')->name('countries.show');
            Route::get('/countries/{id}/edit', 'CountryController@edit')->name('countries.edit');
            Route::post('/countries', 'CountryController@store')->name('countries.store');
            Route::put('/countries/{id}', 'CountryController@update')->name('countries.update');

            //Sellers routes
            Route::get('/sellers', 'SellerController@index')->name('sellers');
            Route::get('/sellers/add', 'SellerController@create')->name('sellers.add');
            Route::get('/sellers/{id}', 'SellerController@show')->name('sellers.show');
            Route::get('/sellers/{id}/edit', 'SellerController@edit')->name('sellers.edit');
            Route::post('/sellers', 'SellerController@store')->name('sellers.store');
            Route::put('/sellers/{id}', 'SellerController@update')->name('sellers.update');
            Route::delete('/sellers/{id}', 'SellerController@destroy')->name('sellers.delete');

            //Images routes
            Route::post('/images', 'ImageController@store')->name('images.store');
            Route::delete('/images/{id}', 'ImageController@delete')->name('images.delete');

            //Videos routes
            Route::post('/videos', 'VideoController@store')->name('videos.store');
            Route::delete('/videos/{id}', 'VideoController@delete')->name('videos.delete');
            Route::put('/videos/{id}', 'VideoController@update')->name('videos.update');
        });
    });
});

app/Http/Controllers/Deep/OrderController.php
<?php

namespace App\Http\Controllers\Deep;

use App\Http\Controllers\Controller;
use App\Http\Requests\OrderStoreRequest;
use App\Http\Requests\OrderUpdateRequest;
use App\Model\Order;
use App\Model\Product;
use App\User;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = Order::all();
        return view('admin.orders.index',['orders' => $orders]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::all(['id', 'name', 'surname']);
        $products = Product::all();
        return view('admin.orders.add', ['products' => $products, 'users' => $users]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(OrderStoreRequest $request)
    {
        $validated = $request->validated();
        // dd($request->user_id);
        $order = new Order();
        $order->quantity = $validated['quantity'];
        $order->product_id = $request->product_id;
        $order->user_id = $request->user_id;
        $order->reference = 'P'.$request->product_id.'I'.crc32(uniqid());
        $order->is_paid = isset($validated['is_paid']);
        $order->is_shipped = isset($validated['is_shipped']);
        $order->is_complete = isset($validated['is_complete']);
        $order->tracking_number = $validated['tracking_number'];
        $order->is_cancelled = false;
        $order->save();
        return redirect(route('deep.orders'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(OrderUpdateRequest $request, $id)
    {
        
        $validated = $request->all();
        // dd($request->user_id);
        $order = Order::all()->find($id);
        if (isset($validated['quantity'])) {
            $order->quantity = $validated['quantity'];
        }
        if (isset($request->product_id)) {
            # code...
            $order->product_id = $request->product_id;
        }
        if (isset($request->user_id)) {
            # code...
            $order->user_id = $request->user_id;
        }
        if (isset($request->is_paid)) {
            # code...
            $order->is_paid = isset($validated['is_paid']);
        }
        if (isset($request->is_shipped)) {
            # code...
            $order->is_shipped = isset($validated['is_shipped']);
        }
        if (isset($request->is_complete)) {
            # code...
            $order->is_complete = isset($validated['is_complete']);
        }
        if (isset($request->is_cancelled) && !$order->is_complete) {
            # code...
            $order->is_cancelled = true;
        }
        // dd('updating',$order);
        $order->save();
        return redirect(route('deep.orders'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/orders/add.blade.php
@extends('admin.layouts.app')

@section('content')
    
@section('content')
<h2>{{ __('Orders Management') }}</h2>

<div class="card my-4">
    <div class="card-header">
        <h6>
            <i class="fas fa-fw fa-table"></i>
            {{ __('Form of products') }}
        </h6>
    </div>
    <div class="card-body">
        @isset($errors)
            @foreach($errors->all() as $error)
            <small class="text-danger">{{$error}}</small><br>
            @endforeach
        @endisset
        <form action="{{ route('deep.orders.store') }}" method="POST">
            @csrf
            <div class="form-group">
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                        <label for="user">Choose customer</label>
                        <input list="users" id="user" name="user" class="form-control  @error('user') is-invalid @enderror"  autocomplete="user"  value="{{ old('user') }}" required>
                        <datalist id="users">
                            @foreach ($users as $user)
                                <option value="{{$user->id.' - '.$user->name.' '.$user->surname}}">
                            @endforeach
                        </datalist>
                        @error('user')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                        {{-- <a href="{{ route('deep.users.add') }}" class="btn btn-link">Add a new customer</a> --}}
                        <a href="#" class="btn btn-link pl-0">Add a new customer</a>
                    </div>

                    <div class="col-sm-12 col-md-6">
                        <label for="product">Choose product</label>
                        <input list="products" id="product" name="product" class="form-control  @error('product') is-invalid @enderror" autocomplete="product"  value="{{ old('product') }}" required>
                        <datalist id="products">
                            @foreach ($products as $product)
                                <option value="{{$product->id.' - '.$product->name}}">
                            @endforeach
                        </datalist>
                        @error('product')
                            <small class="text-danger">{{$message}}</small>
                        @enderror
                        <a href="{{ route('deep.products.add') }}" class="btn btn-link pl-0">Add a new product</a>
                    </div>
                </div>
            </div>
            <div class="form-group">
                
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                        <label for="quantity">Quantity</label>
                        <input type="number" name="quantity" id="quantity" value="{{ old('quantity') }}" class="form-control  @error('quantity') is-invalid @enderror" autocomplete="is_shipped" required>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <label>State</label>
                        <div class="row">
                            <div class="col-sm-12 col-md-4">
                                <div class="form-check  @error('is_paid') is-invalid @enderror">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" name="is_paid" id="is_paid" value="@if(old('is_paid')) {{ old('is_paid') }} @else 1 @endif" checked>
                                    Paid ?
                                </label>
                                </div>
                                @error('is_paid')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="col-sm-12 col-md-4">
                                <div class="form-check  @error('is_shipped') is-invalid @enderror">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" name="is_shipped" id="is_shipped" value="@if(old('is_shipped')) {{ old('is_shipped') }} @else 1 @endif" checked>
                                    Shipped ?
                                </label>
                                </div>
                                @error('is_shipped')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                            <div class="col-sm-12 col-md-4">
                                <div class="form-check  @error('is_complete') is-invalid @enderror">
                                <label class="form-check-label">
                                    <input type="checkbox" class="form-check-input" name="is_complete" id="is_complete" value="@if(old('is_complete')) {{ old('is_complete') }} @else 1 @endif" checked>
                                    Complete ?
                                </label>
                                </div>
                                @error('is_complete')
                                    <small class="text-danger">{{$message}}</small>
                                @enderror
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group pl-0 col-sm-12 col-md-6">
                <label for="tracking_number">Tracking number</label>
                <input type="text" id="tracking_number" class="form-control @error('tracking_number') is-invalid @enderror" name="tracking_number" value="{{ old('tracking_number') }}" autocomplete="tracking_number">
                @error('tracking_number')
                    <small class="text-danger">{{$message}}</small>
                @enderror
            </div>
            <button class="btn btn-success" type="submit">{{ __('Submit') }}</button>
        </form>
    </div>
</div>
@endsection

@section('order-active')active @endsection

resources/views/admin/orders/index.blade.php
@extends('admin.layouts.app')

@section('content')
<h2>{{ __('Orders Management') }}</h2>

<a href="{{ route('deep.orders.add') }}" class="btn btn-success"><i class="fa fa-fw fa-plus"></i> {{ __('Add') }}</a>

<div class="card my-4">
    <div class="card-header">
        <h6>
            <i class="fas fa-fw fa-table"></i>
            {{ __('Table of orders') }}
        </h6>
    </div>
    <div class="card-body">
        @isset($orders)
            @if (count($orders) > 0)
                <table class="table table-bordered table-responsive-md">
                    <thead>
                        <tr>
                            <th>{{ __('Product') }}</th>
                            <th>{{ __('Customer') }}</th>
                            <th>{{ __('Quantity') }}</th>
                            <th>{{ __('Reference') }}</th>
                            <th>{{ __('Paid') }}</th>
                            <th>{{ __('Shipped') }}</th>
                            <th>{{ __('Completed') }}</th>
                            <th>{{ __('Cancelled') }}</th>
                            <th>{{ __('Actions') }}</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>{{ __('Product') }}</th>
                            <th>{{ __('Customer') }}</th>
                            <th>{{ __('Quantity') }}</th>
                            <th>{{ __('Reference') }}</th>
                            <th>{{ __('Paid') }}</th>
                            <th>{{ __('Shipped') }}</th>
                            <th>{{ __('Completed') }}</th>
                            <th>{{ __('Cancelled') }}</th>
                            <th>{{ __('Actions') }}</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach ($orders as $order)
                        <tr>
                            <td>{{ $order->product->name }}</td>
                            <td>{{ $order->user->name }} {{ $order->user->surname }}</td>
                            <td>{{ $order->quantity }}</td>
                            <td>{{ $order->reference }}</td>
                            <td>@if($order->is_paid) <i class="fas fa-check"></i> @else <div class="row py-auto px-2 justify-content-around"><i class="fas fa-times"></i> <form action="{{route('deep.orders.update',$order->id)}}" method="post">@csrf @method('put') <input type="checkbox" checked name="is_paid" hidden> <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-check"></i></button></form> </div>@endif</td>
                            <td>@if($order->is_shipped) <i class="fas fa-check"></i> @else <div class="row py-auto px-2 justify-content-around"><i class="fas fa-times"></i> <form action="{{route('deep.orders.update',$order->id)}}" method="post">@csrf @method('put') <input type="checkbox" checked name="is_shipped" hidden> <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-check"></i></button></form> </div>@endif</td>
                            <td>@if($order->is_complete) <i class="fas fa-check"></i> @else <div class="row py-auto px-2 justify-content-around"><i class="fas fa-times"></i> <form action="{{route('deep.orders.update',$order->id)}}" method="post">@csrf @method('put') <input type="checkbox" checked name="is_complete" hidden> <button type="submit" class="btn btn-success btn-sm"><i class="fas fa-check"></i></button></form> </div>@endif</td>
                            <td>@if($order->is_cancelled) <i class="fas fa-check"></i> @else <div class="row py-auto px-2 justify-content-around"><i class="fas fa-times"></i>@if(!$order->is_complete) <form action="{{route('deep.orders.update',$order->id)}}" method="post">@csrf @method('put') <input type="checkbox" checked name="is_cancelled" hidden> <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-check"></i></button></form> @endif</div>@endif</td>
                            <td>
                                <div class="row px-3 justify-content-arround">
                                    <a href="{{ route( 'deep.orders.show' , $order->id ) }}" class="btn btn-primary rounded mr-1 mb-1"><i class="fas fa-file"></i></a>
                                    <a href="{{ route( 'deep.orders.edit' , $order->id ) }}" class="btn btn-warning rounded mr-1 mb-1"><i class="fas fa-pen"></i></a>
                                    <button class="btn btn-danger rounded mr-1 mb-1"><i class="fas fa-trash"></i></button>
                                </div>
                            </td>
                        </tr>    
                        @endforeach
                    </tbody>
                    
                </table>
            @else
            <div class="alert alert-info">
                <h3>{{ __('Info') }}</h3>
                <p>{{ __('No order found in the database') }}</p>
            </div>
            @endif
        @else
        <div class="alert alert-danger">
            <h3>{{ __('Error') }}</h3>
            <p>{{ __('We have been unable to fetch orders data') }}</p>
        </div>
        @endisset
    </div>
</div>
@endsection

@section('order-active')active @endsection